name: Sync Categories

on:
  repository_dispatch:
    types: [sync-categories]
  workflow_dispatch:

jobs:
  sync-categories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: corepack install
      - name: Run pnpm install
        run: pnpm install --frozen-lockfile --recursive
      - run: pnpm build
      - run: pnpm action sync-categories
        env:
          HOSTNAME: ${{ vars.HOSTNAME }}
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_PRIVATE_KEY: ${{ secrets.ALGOLIA_PRIVATE_KEY }}
          ALGOLIA_INDEX_CATEGORIES: ${{ vars.ALGOLIA_INDEX_CATEGORIES }}
          WOOCOMMERCE_KEY: ${{ secrets.WOOCOMMERCE_KEY }}
          WOOCOMMERCE_SECRET: ${{ secrets.WOOCOMMERCE_SECRET }}
