name: Sync Menu Items

on:
  repository_dispatch:
    types: [sync-menu-items]
  workflow_dispatch:

jobs:
  sync-menu-items:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: corepack install
      - name: Run pnpm install
        run: pnpm install --frozen-lockfile --recursive
      - run: pnpm build
      - run: pnpm action sync-menu-items
        env:
          HOSTNAME: ${{ vars.HOSTNAME }}
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_PRIVATE_KEY: ${{ secrets.ALGOLIA_PRIVATE_KEY }}
          ALGOLIA_INDEX_MENU_ITEMS: ${{ vars.ALGOLIA_INDEX_MENU_ITEMS }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
